---
title: 'Milestone #2'
author: "Sabrina Goldfischer"
date: "9/22/2020"
output: html_document
---

Link to GitHub: https://github.com/sgoldfischer/milestone2.git

The first project I looked at was "Agriculture and Education in the Midwest" by Julia Englebert (link: https://julia-englebert.shinyapps.io/midwest_edu_ag/). I selected this project to look at because she mentioned she used census data and mapping, two tools I plan on using for my own final project. Since her project's theme was also related to education, I thought it could be helpful to see her visualizations, as I plan to study education in the City of Poughkeepsie. Although this class is my first exposure to shiny apps, I did see some pros and cons (but she did do a fantastic job!!). Some pros were her use of animations to show changes overtime. I thought this was a very clear way to show the changes she was bringing to light, and it looks super professional. I like how she also aligned colors to states, which was helpful in interpreting her visualizations Some cons were that it was a bit overwhelming to see all the lines for every state on the graphs at once -- I wish she had a drop down where you could also see individual changes for each state over time. I also found her visual under "Farms and Acreage" for Average Farmland Acreage over Time" to be sort of confusing to interpret. My goal is to be able to share my visualizations with Poughkeepsie residents, so I want to make sure it is super easy and clear to interpret! She did an amazing job though, her project is really inspiring. 

The second project I looked at was "Common Core Standards (CCS) Implementation in the US" by Jenna Moustafa (link: https://jenna-moustafa.shinyapps.io/CommonCoreStandardsRacialAchievementGap/). I once again decided to click on this project because it was related to education!! I found her project to be super impressive. Some pros: I like how I can switch to different tabs to see different visualizations. I think this is a super helpful way to navigate the different factors she studies. I also love the state dropdown, I think this is an incredible way to visualize data and after seeing these projects, I definitely want to include it in my own! One con I had was her visualizations for "Outcomes for Non-White Students by State and Test," as I found it pretty hard to understand. For someone without a statistical background, it did not make too much sense to me, and I think there could have been better ways to visualize this data. However, this was another awesome project!! Both Julia and Jenna's work is extremely impressive, and I hope I can make an equally awesome final project. 
